### PR TITLE
Fix build with ITK 5

### LINKED ISSUE #55: PETPVC does not build with ITK 5
`itk::CylinderSpatialObject` does not seem to exist in ITK 5 and so `CreateTestImage.cxx` cannot be built.

### PR DESCRIPTION
**Pull request by ghisvail**
Following suggestions in https://discourse.itk.org/t/replacement-for-cylinderspatialobject/3771/2

Closes #55

### CODE REVIEW

**Comment by ghisvail** [comment]
I have made it so the tests can still be built with ITK 4.

**Comment by ghisvail** [comment]
Look like the MacOS CI branch is struggling with building ITK 5. It might be worth to also upgrade the build to ITK version 5.2.

**Comment by ghisvail** [comment]
> Look like the MacOS CI branch is struggling with building ITK 5.

My bad, it seems that it's more to do with the MacOS tool chain.

After googling some of the error messages, it looks like there might be some more CMake configuration required specifically for MacOS. See this [post](https://github.com/blender/blender/blob/master/build_files/cmake/platform/platform_apple_xcode.cmake) on the Blender forum.

**Comment by KrisThielemans** [comment]
thanks a lot!

let's keep the discussion on the MacOS problems in #64

**Pull request merged**
