### PR TITLE
Use ITK 5.2.0 for CI

### PR DESCRIPTION
**Pull request by KrisThielemans**
@ghisvail are you aware of any other changes needed? (e.g. do we still need the ITKReview module?)

### CODE REVIEW

**Comment by KrisThielemans** [comment]
Still the same problem #64 (`brew` is still using ITK 5.1 anyway)

**Comment by ghisvail** [comment]
To be honest, I'd rather trust my own install of third-party dependencies or official packages in Linux distributions for CI than Homebrew.

**Comment by KrisThielemans** [comment]
sure. but on MacOS there is no official package manager I suppose. Anyway, we know via the Travis build that it isn't really a PETPVC problem. I might flag this up on the `brew` webpage. Seems they put in a fix for VTK. https://github.com/Homebrew/homebrew-core/pull/60380. Maybe it's needed for ITK as well.

**Comment by ghisvail** [comment]
We'll see whether I hit the same issue with the conda-forge package on MacOS

**Comment by ghisvail** [comment]
> do we still need the ITKReview module?

You are still using `LabelGeometryImageFilter`, so yes you do.

**Comment by KrisThielemans** [comment]
This all works fine, except of course the azure macos build. Phew!

@bathomas @ghisvail it could be worth keeping some CI builds with older ITK versions. Any opinion?

**Comment by ghisvail** [comment]
> Any opinion?

I think we are still going to live with ITK v4.13 around for a while, at least in Debian / Ubuntu land. With that in mind it's probably worth to keep testing for Linux at the very least.

**Comment by KrisThielemans** [comment]
fair enough. So now Travis and appveyor use 5.2.0, but azure-pipelines use (as before) 
- `apt libinsighttoolkit` on Ubuntu 16.04
- `brew` on MacOs
- ITK 4.13.1 on Windows

**Comment by ghisvail** [comment]
Fyi, no problem with OSX builds on [conda-forge](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=329854&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7). It builds and tests fine.

**Comment by KrisThielemans** [comment]
Interesting. i see that conda already [uses ITK 5.2.0.](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=329854&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310&l=1003). that looks promising...

**Comment by bathomas** [comment]
> This all works fine, except of course the azure macos build. Phew!
> 
> @bathomas @ghisvail it could be worth keeping some CI builds with older ITK versions. Any opinion?

I don't have a strong opinion really. Probably best not to maintain older versions.

**Pull request merged**
